dependencies:
# build
  - python >=3.9
  - numpy >=2.0
  - ipopt
  - swig
  - meson >=1.3.2
  - meson-python
  - compilers
  - pkg-config
  - pip
  - setuptools
  - build
  - flang 5*
  - libpgmath
# runtime
  - packaging
  - mdolab-baseclasses >=1.3.1
  - scipy >=1.7
  - sqlitedict >=1.6
# testing
  - parameterized
  - testflo
