dependencies:
# build
  - python >=3.8
  - numpy >=1.16
  - ipopt
  - swig
  - meson >=1.3.1
  - compilers
  - flang
  - pkg-config
  - pip
  - setuptools
  - build
# testing
  - parameterized
  - testflo
  - scipy >1.2
  - mdolab-baseclasses >=1.3.1
  - sqlitedict >=1.6